### ISSUE TITLE
New warnings in version of 3/12/2019

### ISSUE THREAD

**Issue by fredplunkett** [Moskus/hspi_CsharpSample#5]
The version posted 3/12/2019 builds and runs locally "out-of-the-box".  However, the build generates the warnings below in VS2017.  Maybe this is all "future use"stuff, but I thought it worth mentioning.

Severity	Code	Description	Project	File	Line	Suppression State	Detail Description

Warning	CS0108	'HSPI.ActionAdvancedMode' hides inherited member 'HspiBase.ActionAdvancedMode'. Use the new keyword if hiding was intended.	hspi_CsharpSample	C:\Homeseer Projects\HSPI_CsharpMoskusSample_V1\hspi_CsharpSample-master\hspi_CsharpSample\Hspi.cs	571	Active	A variable was declared with the same name as a variable in a base class. However, the new keyword was not used. This warning informs you that you should use new; the variable is declared as if new had been used in the declaration.

Warning	CS0169	The field 'Program._instance' is never used	hspi_CsharpSample	C:\Homeseer Projects\HSPI_CsharpMoskusSample_V1\hspi_CsharpSample-master\hspi_CsharpSample\Program.cs	34	Active

Warning	CS0169	The field 'Program._appApi' is never used	hspi_CsharpSample	C:\Homeseer Projects\HSPI_CsharpMoskusSample_V1\hspi_CsharpSample-master\hspi_CsharpSample\Program.cs	35	Active

Warning	CS0169	The field 'Program._host' is never used	hspi_CsharpSample	C:\Homeseer Projects\HSPI_CsharpMoskusSample_V1\hspi_CsharpSample-master\hspi_CsharpSample\Program.cs	36	Active

Warning	CS0169	The field 'Program._callback' is never used	hspi_CsharpSample	C:\Homeseer Projects\HSPI_CsharpMoskusSample_V1\hspi_CsharpSample-master\hspi_CsharpSample\Program.cs	37	Active

Warning	CS0169	The field 'Program._utils' is never used	hspi_CsharpSample	C:\Homeseer Projects\HSPI_CsharpMoskusSample_V1\hspi_CsharpSample-master\hspi_CsharpSample\Program.cs	38	Active

**Comment by oesolberg** [comment]
Thanks for the heads up. Just some variables I forgot to remove. Removed now.
