### ISSUE TITLE
Getting System.BadImageFormatException when Trying to Build from Fresh Download

### ISSUE THREAD

**Issue by royf007** [Moskus/hspi_CsharpSample#6]
Hi, I'm getting the following exception: `System.BadImageFormatException` when Trying to Build from Fresh Download.  I'm using Visual Studio 2017 Community Edition, have HomeSeer 3.0.0.500 running locally, and I have copied the 3 DLLs from the HomeSeer local installation to the solution lib folder:

Here are the full details:

`System.BadImageFormatException: 'Could not load file or assembly 'HomeSeerAPI, Version=1.0.2.1, Culture=neutral, PublicKeyToken=null' or one of its dependencies. An attempt was made to load a program with an incorrect format.'`

**Comment by royf007** [comment]
Ok, it was a noob issue.  I solved it by changing the Platform Target to "Prefer 32-bit" on the Solution Properties.  Works great now!

![HSPI_VS_Build_Fix_20190313](https://user-images.githubusercontent.com/4976402/54308189-d3fbef80-45a3-11e9-9396-7b6572d8ea28.png)

**Comment by oesolberg** [comment]
Thanks for the heads up. Added explanation to the readme.
